package com.string.easy;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class FindTheDifference {
    /*
     * 389. Find the Difference
     * 
     * String t is generated by random shuffling string s and then add one more
     * letter at a random position.
     * 
     * Input: s = "abcd", t = "abcde"
     * Output: "e"
     * Explanation: 'e' is the letter that was added.
     * 
     * Input: s = "", t = "y"
     * Output: "y"
     */

    public static void main(String... args) throws Exception {
        String s = "ae", t = "aea";
        System.out.println(findTheDifference(s, t));
    }

    public static char findTheDifference(String s, String t) {

        char[] ch1 = s.toCharArray(), ch2 = t.toCharArray();
        int sum_s = 0, sum_t = 0;
        for (char c : ch1)
            sum_s += (int) c;
        for (char c : ch2)
            sum_t += (int) c;
        return (char) (sum_t - sum_s);
    }

    public static char findTheDifference2(String s, String t) {

        // Initialize variables to store sum of ASCII codes
        int charCodeS = 0, charCodeT = 0;

        for (int i = 0; i < s.length(); ++i)
            charCodeS += (int) s.charAt(i);
        for (int i = 0; i < t.length(); ++i)
            charCodeT += (int) t.charAt(i);
        // Return the difference between 2 strings as char
        return (char) (charCodeT - charCodeS);

        // int charCode = t.charAt(s.length());
        // // Iterate through both strings and char codes
        // for (int i = 0; i < s.length(); ++i) {
        // charCode -= (int)s.charAt(i);
        // charCode += (int)t.charAt(i);
        // }
        // return (char)charCode;

    }

}